const FETCH_WELCOME_DATA = 'localExample/FETCH_WELCOME_DATA';
const FETCH_WELCOME_DATA_SUCCESS = 'localExample/FETCH_WELCOME_DATA_SUCCESS';
const FETCH_WELCOME_DATA_ERROR = 'localExample/FETCH_WELCOME_DATA_ERROR';

export {
  FETCH_WELCOME_DATA,
  FETCH_WELCOME_DATA_ERROR,
  FETCH_WELCOME_DATA_SUCCESS,
};
