// internal API
const FETCH_INTERNAL_WELCOME_DATA = 'localExample/FETCH_INTERNAL_WELCOME_DATA';
const FETCH_INTERNAL_WELCOME_DATA_ERROR =
  'localExample/FETCH_INTERNAL_WELCOME_DATA_ERROR';
const FETCH_INTERNAL_WELCOME_DATA_SUCCESS =
  'localExample/FETCH_INTERNAL_WELCOME_DATA_SUCCESS';

// public API
const FETCH_PUBLIC_WELCOME_DATA = 'localExample/FETCH_PUBLIC_WELCOME_DATA';
const FETCH_PUBLIC_WELCOME_DATA_SUCCESS =
  'localExample/FETCH_PUBLIC_WELCOME_DATA_SUCCESS';
const FETCH_PUBLIC_WELCOME_DATA_ERROR =
  'localExample/FETCH_PUBLIC_WELCOME_DATA_ERROR';

export {
  // internal API
  FETCH_INTERNAL_WELCOME_DATA,
  FETCH_INTERNAL_WELCOME_DATA_ERROR,
  FETCH_INTERNAL_WELCOME_DATA_SUCCESS,

  // public API
  FETCH_PUBLIC_WELCOME_DATA,
  FETCH_PUBLIC_WELCOME_DATA_ERROR,
  FETCH_PUBLIC_WELCOME_DATA_SUCCESS,
};
