// internal API
const SET_INTERNAL_WELCOME_PUBLIC_DATA =
  'welcome/SET_INTERNAL_WELCOME_PUBLIC_DATA';
const SET_INTERNAL_WELCOME_PROTECTED_DATA =
  'welcome/SET_INTERNAL_WELCOME_PROTECTED_DATA';

// external API
const SET_EXTERNAL_WELCOME_PUBLIC_DATA =
  'welcome/SET_EXTERNAL_WELCOME_PUBLIC_DATA';

export {
  // external API
  SET_EXTERNAL_WELCOME_PUBLIC_DATA,
  // internal API
  SET_INTERNAL_WELCOME_PROTECTED_DATA,
  SET_INTERNAL_WELCOME_PUBLIC_DATA,
};
